import { JetBrains_Mono } from "next/font/google";
import MainNav from "../components/MainNav"
import PageTransition from "../components/PageTransitions";
import ScreenTransition from "../components/ScreenTransition";
import "./globals.css";

const jetBrainsMono = JetBrains_Mono({ 
  subsets: ["latin"],
  weight: ['100','200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetbrainsMono'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.variable} antialiased overflow-hidden relative`}>
        <ScreenTransition/>
        <PageTransition>
          <div className="flex">
            {/*main navbar*/}
            <div
              className="hidden xl:flex w-[285px] h-screen bg-secondary"
            >
              <MainNav />
            </div>
            <div className="w-full max-w-[1130px] px-[15px] mx-auto">
              <header>
                header
              </header>
              <div>{children}</div>
            </div>
          </div>
        </PageTransition>
      </body>
    </html>
  );
}
